[project]
name = "chatbot"
version = "0.1.0"
description = "Chatbot asistente para PYME de recuerdos de mascotas"
authors = [
    { name = "Julio Muñoz" },
    { name = "Asistido por IA: Copilot y Gemini" }
]
requires-python = ">=3.10"
dependencies = [
    "google-genai",
    "mysql-connector-python",
    "streamlit",
    "python-dotenv",
    "pytest"
]
[tool.pytest.ini_options]
testpaths = ["tests"]